### ISSUE TITLE
Develop a interactive Menu Function for the Theatre_Management_system

### ISSUE THREAD

**Issue by surajmax0101** [surajmax0101/Theatre_Management_System#1]
**Details** 👍 

- Scroll UI 
- Up down action with arrow keys or W/S 
- Wrapping (*special)
- Colours (**conio.h** only)
- **No external graphics library** allowed (**graphics.h** etc.)
- **Turbo C** Standard Compiler to be used for testing as well as developement 

NOTE :  Not conforming may cause your PR to be rejected.

**Comment by thisiskartikgupta** [comment]
Hi @surajmax0101 , I have worked on management systems in C in the past. I'd love to contribute. It would be great if we could get some information on how to contribute to Theatre Management System.

**Comment by surajmax0101** [comment]
@thisiskartikgupta  Thanks for your interest. We will be pushing our README soon. Star the repository to receive updates regarding the same.

Thanks,
Suraj (@surajmax0101 )

**Comment by thisiskartikgupta** [comment]
Hey, I would like to work on this. Please assign me this issue. I have worked on C++ projects before.

**Comment by surajmax0101** [comment]
Issue solved via merge with @thisiskartikgupta .
