### ISSUE TITLE
Create Animation in C for Load Screen/Exit Screen/ Etc.

### ISSUE THREAD

**Issue by surajmax0101** [surajmax0101/Theatre_Management_System#2]
- Ensure smoothness.
- Frame Transition By clrscr() or system("cls") only 

No conformation to the above rules will lead to disqualification of the PR

**Comment by thisiskartikgupta** [comment]
@surajmax0101 , Can I work on this one ?

**Comment by thisiskartikgupta** [comment]
Can you give some idea about the type of animations that would be required ?

**Comment by surajmax0101** [comment]
Go through the code and try to create something that suits the application. Only you define your limits now.

**Comment by surajmax0101** [comment]
@thisiskartikgupta solved it by latest pull request.
